export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export EDITOR="nvim"
export VISUAL="${EDITOR}"

export DO_NOT_TRACK=1
export HOMEBREW_NO_ANALYTICS=1

export HISTFILE="${ZDOTDIR}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000

export VENV_HOME="${HOME}/.venvs"

# wrk
export AWS_CA_BUNDLE="${HOME}/.certs/FW_BUNDLE.crt"
